### ISSUE TITLE
Syntax highlighting doesn't support block comment

### ISSUE THREAD

**Issue by subhammridha** [Gimly/vscode-matlab#13]
Newer matlab versions have the ability to comment blocks of text using `%{` and `%}`.
But this type of syntax doesn't seems to be supported.
Could you please incorporate that?

**Comment by amauragis** [comment]
Check out #7.  I think this is a known bug being worked on.

**Comment by Gimly** [comment]
It is supported, it just doesn't work completely as it should, as per issue #7. 

If you don't mind, I'm going to close this issue as it's already discussed in this issue.

If you feel the issue you're having is not exactly the same issue, please re-open another issue including more information (like some code and a screenshot) so that I can reproduce the issue you're facing. Thanks!
