### ISSUE TITLE
linter does not work with VSCode 0.10.5

### ISSUE THREAD

**Issue by michalkvasnicka** [Gimly/vscode-matlab#2]
After successful install and configuration of vscode-matlab extention to VScode 0.10.5 the linter does not work. No errors are highlighted!!!

Any help?

**Comment by michalkvasnicka** [comment]
Any respond from the author of VScode-matlab extension???

**Comment by Gimly** [comment]
Hi Michal,

Sorry about the late answer, I was very busy on other things these last days. I can't also check right now what might be the issue, as I'm on vacation and don't have access to Matlab...

But, except from a breaking change on VS Code's latest version, it should be working correctly.

First, please check that you've given the correct path to the linter in the configuration file. To test, you can actually open a command prompt, and write

`"the path to your linter that you've entered in the config file/mlint.exe" "path to your Matlab file"`

This should give you a return with all the errors / issues in your code formatted in mlint's special way. If it doesn't work, try to fix the path and try again in VS Code.

Then, if it still doesn't work, make sure that the type of document in VS Code is indeed Matlab. .m File extension is also linked to Objective C's "method" files and, since VS Code also supports those files, it sometimes thinks it's an Objective C file instead of a Matlab file. You can see that at the bottom-right corner of VS Code, it should be written Matlab.

Finally, keep in mind that the linting is actually only executed on save. So, when you first open the document it doesn't show any error / issue. You'll have to do a change (add a space somewhere and delete it) and save again to make the linting trigger.

I hope this was helpful to you. If it still doesn't work, please tell me and I'll try to find a solution to test it again with the latest version of VS Code. Thanks for your help and patience.

I wish you Happy Holidays.

**Comment by michalkvasnicka** [comment]
This is the reason:
"Finally, keep in mind that the linting is actually only executed on save. So, when you first open the document it doesn't show any error / issue. You'll have to do a change (add a space somewhere and delete it) and save again to make the linting trigger."

Thanks a  lot for help! Could be possible to activate mlint immediately after file opening, too?

**Comment by Gimly** [comment]
Yes, I'll try to do this for the next version, it's a good remark.

**Comment by Gimly** [comment]
The new version 0.4.0 should now run the linter when opening the file.
